
package csssr_autotest.soap_api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompanyResourceService", targetNamespace = "http://csssr.com/definitions", wsdlLocation = "https://soap.qa-test.csssr.com/ws/soap.wsdl")
public class CompanyResourceService
    extends Service
{

    private final static URL COMPANYRESOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPANYRESOURCESERVICE_EXCEPTION;
    private final static QName COMPANYRESOURCESERVICE_QNAME = new QName("http://csssr.com/definitions", "CompanyResourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://soap.qa-test.csssr.com/ws/soap.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANYRESOURCESERVICE_WSDL_LOCATION = url;
        COMPANYRESOURCESERVICE_EXCEPTION = e;
    }

    public CompanyResourceService() {
        super(__getWsdlLocation(), COMPANYRESOURCESERVICE_QNAME);
    }

    public CompanyResourceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANYRESOURCESERVICE_QNAME, features);
    }

    public CompanyResourceService(URL wsdlLocation) {
        super(wsdlLocation, COMPANYRESOURCESERVICE_QNAME);
    }

    public CompanyResourceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANYRESOURCESERVICE_QNAME, features);
    }

    public CompanyResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompanyResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompanyResource
     */
    @WebEndpoint(name = "CompanyResourcePort")
    public CompanyResource getCompanyResourcePort() {
        return super.getPort(new QName("http://csssr.com/definitions", "CompanyResourcePort"), CompanyResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompanyResource
     */
    @WebEndpoint(name = "CompanyResourcePort")
    public CompanyResource getCompanyResourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://csssr.com/definitions", "CompanyResourcePort"), CompanyResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANYRESOURCESERVICE_EXCEPTION!= null) {
            throw COMPANYRESOURCESERVICE_EXCEPTION;
        }
        return COMPANYRESOURCESERVICE_WSDL_LOCATION;
    }

}
