
package csssr_autotest.soap_api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CompanyResource", targetNamespace = "http://csssr.com/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompanyResource {


    /**
     * 
     * @param addCompanyRequest
     * @return
     *     returns csssr_autotest.soap_api.AddCompanyResponse
     */
    @WebMethod(operationName = "AddCompany")
    @WebResult(name = "AddCompanyResponse", targetNamespace = "http://csssr.com/schemas", partName = "AddCompanyResponse")
    public AddCompanyResponse addCompany(
        @WebParam(name = "AddCompanyRequest", targetNamespace = "http://csssr.com/schemas", partName = "AddCompanyRequest")
        AddCompanyRequest addCompanyRequest);

    /**
     * 
     * @param getCompanyRequest
     * @return
     *     returns csssr_autotest.soap_api.GetCompanyResponse
     */
    @WebMethod(operationName = "GetCompany")
    @WebResult(name = "GetCompanyResponse", targetNamespace = "http://csssr.com/schemas", partName = "GetCompanyResponse")
    public GetCompanyResponse getCompany(
        @WebParam(name = "GetCompanyRequest", targetNamespace = "http://csssr.com/schemas", partName = "GetCompanyRequest")
        GetCompanyRequest getCompanyRequest);

    /**
     * 
     * @param addEmployeeRequest
     * @return
     *     returns csssr_autotest.soap_api.AddEmployeeResponse
     */
    @WebMethod(operationName = "AddEmployee")
    @WebResult(name = "AddEmployeeResponse", targetNamespace = "http://csssr.com/schemas", partName = "AddEmployeeResponse")
    public AddEmployeeResponse addEmployee(
        @WebParam(name = "AddEmployeeRequest", targetNamespace = "http://csssr.com/schemas", partName = "AddEmployeeRequest")
        AddEmployeeRequest addEmployeeRequest);

    /**
     * 
     * @param addEmployeesToCompanyRequest
     * @return
     *     returns csssr_autotest.soap_api.AddEmployeesToCompanyResponse
     */
    @WebMethod(operationName = "AddEmployeesToCompany")
    @WebResult(name = "AddEmployeesToCompanyResponse", targetNamespace = "http://csssr.com/schemas", partName = "AddEmployeesToCompanyResponse")
    public AddEmployeesToCompanyResponse addEmployeesToCompany(
        @WebParam(name = "AddEmployeesToCompanyRequest", targetNamespace = "http://csssr.com/schemas", partName = "AddEmployeesToCompanyRequest")
        AddEmployeesToCompanyRequest addEmployeesToCompanyRequest);

    /**
     * 
     * @param updateEmployeeRequest
     * @return
     *     returns csssr_autotest.soap_api.UpdateEmployeeResponse
     */
    @WebMethod(operationName = "UpdateEmployee")
    @WebResult(name = "UpdateEmployeeResponse", targetNamespace = "http://csssr.com/schemas", partName = "UploadEmployeeResponse")
    public UpdateEmployeeResponse updateEmployee(
        @WebParam(name = "UpdateEmployeeRequest", targetNamespace = "http://csssr.com/schemas", partName = "UpdateEmployeeRequest")
        UpdateEmployeeRequest updateEmployeeRequest);

}
